models/News.php
<?php

namespace app\models;

use app\models\base\NewsBase;
use Exception;
use Yii;
use yii\behaviors\SluggableBehavior;
use yii\helpers\ArrayHelper;
use yii\web\UploadedFile;
use yii\imagine\Image;

class News extends NewsBase
{
    /**
     * @var UploadedFile
     */
    public $file;

    public function behaviors()
    {
        return [
            [
                'class' => SluggableBehavior::class,
                'attribute' => 'title',
                'slugAttribute' => 'slug',
                'ensureUnique' => true,
            ],
        ];
    }

    public function rules()
    {
        return ArrayHelper::merge(parent::rules(), [
            [['file'], 'required'],
            [
                ['file'],
                'file',
                'skipOnEmpty' => true,
                'extensions' => ['png', 'jpg'],
                'maxSize' => 2 * 1024 * 1024, //2 MB
                'checkExtensionByMimeType' => true
            ]
        ]);
    }

    public function beforeValidate()
    {
        $this->file = UploadedFile::getInstance($this, 'file');

        if (!empty($this->file) && ($this->file instanceof UploadedFile)) {
            $this->file_name = $this->generateUniqueFileName($this->file->getExtension());
        }

        return parent::beforeValidate();
    }

    public function beforeSave($event)
    {
        if (parent::beforeSave($event)) {
            if (!empty($this->file)) {

                $path = Yii::$app->params['upload_dir'] . DIRECTORY_SEPARATOR;

                if (!$this->isNewRecord && is_file($path . $this->getOldAttribute('file_name'))) {
                    unlink($path . $this->getOldAttribute('file_name'));
                }

                if (!$this->isNewRecord && is_file($path . 'thumbnail' . DIRECTORY_SEPARATOR . $this->getOldAttribute('file_name'))) {
                    unlink($path . 'thumbnail' . DIRECTORY_SEPARATOR . $this->getOldAttribute('file_name'));
                }

                $this->file->saveAs($path . $this->file_name);

                Image::thumbnail($path . $this->file_name, 150, 150)
                    ->save($path . 'thumbnail' . DIRECTORY_SEPARATOR . $this->file_name);

            }
            return true;
        }
    }

    public function generateUniqueFileName($extension = 'jpg', $length = 24)
    {
        try {
            $randomString = Yii::$app->getSecurity()->generateRandomString($length) . '.' . $extension;

            if (!self::findOne(['file_name' => $randomString])) {
                return $randomString;
            } else {
                return $this->generateUniqueFileName($extension, $length);
            }

        } catch (Exception $e) {
            Yii::error($e->getMessage());
        }
    }
}

controllers/NewsController.php
<?php

namespace app\controllers;

use app\models\base\ActiveRecordStatus;
use Yii;
use app\models\News;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * NewsController implements the CRUD actions for News model.
 */
class NewsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['list', 'item'],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @return string
     */
    public function actionList()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => News::find()
                ->where(['status' => ActiveRecordStatus::STATUS_ACTIVE])
                ->orderBy('cr_date DESC'),
            'pagination' => [
                'pageSize' => 20,
            ],
        ]);

        return $this->render('list', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionItem($slug)
    {
        $model = News::find()
            ->where([
                'status' => ActiveRecordStatus::STATUS_ACTIVE,
                'slug' => $slug
            ])->one();
        if (!empty($model)) {
            return $this->render('item', [
                'model' => $model,
            ]);
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }


    /**
     * Lists all News models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => News::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Creates a new News model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new News();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing News model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionAjaxView($id)
    {
        return $this->renderAjax('_view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Deletes an existing News model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $model->status = News::STATUS_DELETED;
        $model->save(false);
    }

    /**
     * Finds the News model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return News the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = News::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionAttachmentDelete($id)
    {
        try {
            $model = $this->findModel($id);
            $path = Yii::$app->params['upload_dir'] . DIRECTORY_SEPARATOR;
            if (is_file($path . $model->file_name)) {
                unlink($path . $model->file_name);
            }
            if (is_file($path . 'thumbnail' . DIRECTORY_SEPARATOR . $model->file_name)) {
                unlink($path . 'thumbnail' . DIRECTORY_SEPARATOR . $model->file_name);
            }
            $model->file_name = '';
            $model->save(false);
        } catch (NotFoundHttpException $e) {
            Yii::error($e->getMessage());
            echo "Nem várt hiba történt, kérlek probáld meg később.";
        }
    }

}

views/news/_form.php
<?php

use app\models\base\ActiveRecordStatus;
use dosamigos\ckeditor\CKEditor;
use kartik\file\FileInput;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\News */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="news-form">

    <?php $form = ActiveForm::begin([
      'options' => [
              'enctype' => 'multipart/form-data',
      ]
    ]); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'teaser')->textarea(['rows' => 4]) ?>

    <?= $form->field($model, 'body')->widget(CKEditor::class, [
      'options' => ['rows' => 6],
      'preset' => 'basic'
    ]); ?>

    <?php
    try {
        echo FileInput::widget( [
          'model'         => $model,
          'attribute'     => 'file',
          'pluginLoading' => true,
          'options'       => [
            'multiple'             => false,
            'id'                   => 'file-input',
            'data-msg-placeholder' => 'Fájl kiválasztása'
          ],
          'pluginOptions' => [
            'allowedFileExtensions' => [ 'png', 'jpg', 'jpeg' ],
            'initialPreview' => !$model->isNewRecord ? '/upload/' . $model->file_name : '',
            'initialPreviewConfig' => !$model->isNewRecord ? [
              'caption' => $model->title,
              'key' => $model->id,
              'url' => '/news/attachment-delete'
            ] : '',
            'initialPreviewAsData'  => true,
            'showUpload'            => false,
            'maxFileSize'           => 2048,
            'showPreview'           => true,
            'showRemove'            => true,
            'fileActionSettings'    => [
              'showRemove' => true,
              'showDrag'   => false,
            ],
          ],

        ] );
    } catch ( \Exception $e ) {
        Yii::error( $e->getMessage() );
        echo "Nem várt hiba történt, kérlek probáld meg később.";
    }
    ?>


    <?= $form->field($model, 'status')->dropDownList(ActiveRecordStatus::statusLabels()) ?>

    <div class="form-group">
      <?= Html::submitButton($model->isNewRecord
        ? 'Mentés' : 'Módosítás',
        ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/news/_news.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $model app\models\News */
?>
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="news-teaser">
                <img src="/upload/thumbnail/<?= $model->file_name?>" >
                <div>
                    <h3><?= Html::encode($model->title) ?></h3>
                    <?= Html::encode($model->teaser) ?>
                    <div><?= $model->cr_date ?></div>
                </div>
            </div>
        </div>
        <a href="/hir/<?= Html::encode($model->slug) ?>" title="<?= Html::encode($model->title) ?>" class="btn btn-primary next">Tovább</a>
    </div>

views/news/_view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\News */
?>

<div class="well">

	<?php try {
	    echo DetailView::widget([
			'model' => $model,
			'attributes' => [
				'id',
				'title',
				'slug',
				'teaser',
				[
					'attribute' => 'cr_user',
					'value' => $model->crUser !== null ? $model->crUser->name : null,
				],
				'cr_date',
				[
					'attribute' => 'mod_user',
					'value' => $model->modUser !== null ? $model->modUser->name : null,
					'visible' => $model->modUser !== null
				],
				[
					'attribute' => 'mod_date',
					'value' => $model->mod_date,
					'visible' => $model->mod_date !== null
				],
				[
					'attribute' => 'status',
					'value' => $model->getStatus(),
				],
			],
		]);
    } catch (\Exception $e ) {
		echo "Sajnos hiba történt, kérlek próbáld meg késöbb újra! " . $e->getMessage();
    }
    ?>

</div>

views/news/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\News */

$this->title = 'Hír létrehozása';
$this->params['breadcrumbs'][] = ['label' => 'Hírek', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="news-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/news/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Hírek';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="news-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Hír létrehozása', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'title',
            'slug',
            'cr_date',
            [
                'attribute' => 'status',
                'value' => function($model) {
                    return $model->getStatus();
                },
            ],

          [
            'header' =>  'Műveletek',
            'class' => 'yii\grid\ActionColumn',
            'buttons' => [
              'view' => function ($url, $model, $key) {
                return Html::a('<span class="glyphicon glyphicon-eye-open"></span>','#', [
                  'title' => 'Megtekintés',
                  'class' => 'activity-view-link',
                  'data-id' => $key,
                  'data-url' => $url,
                  'data-title' => 'Felhasználó megtekintése',
                  'data-pjax' => '0',
                ]);
              },
              'delete' => function ($url, $model, $key) {
                return $model->status !== $model::STATUS_DELETED ?
                  Html::a('<span class="glyphicon glyphicon-trash"></span>','#', [
                    'title' => 'Törlés',
                    'class' => 'activity-delete-link',
                    'data-id' => $key,
                    'data-url' => $url,
                    'data-text' => Yii::t('app', 'törlöd {title} hírt?',
                      ['title' => $model->title]),
                    'data-pjax' => '0',
                  ]) : '';
              },
            ],
          ],
        ],
    ]); ?>

    <?php Pjax::end(); ?>

</div>
<?php
echo $this->render('@app/views/layouts/_modals');

views/news/item.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $model app\models\News */

?>
<div class="news">

    <h1><?= Html::encode($model->title) ?></h1>
    <div><img src="/upload/<?= $model->file_name ?>" title="<?= Html::encode($model->title) ?>" class="img-responsive"></div>
    <div><?= Html::encode($model->teaser) ?></div>
    <div><?= $model->body ?></div>
    <?= Html::a('Vissza', ['/'], ['class'=>'btn btn-primary']) ?>

</div>

views/news/list.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Hírek';
?>
<div class="news-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php Pjax::begin(); ?>
    <?php
    echo ListView::widget([
        'dataProvider' => $dataProvider,
        'itemView' => '_news',
    ]);
    ?>

    <?php Pjax::end(); ?>

</div>

views/news/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\News */

$this->title = 'Update News: ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'News', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="news-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>